### ISSUE TITLE
Problem: We haven't an ADR describing Archivematica's original design principles

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/archivematica-architectural-decisions#21]
In our team-meeting 16 December 2019 _(ref: AM weekly 2019-12-16)_ it was decided an ADR would be drafted that describes Archivematica's original design principles. Through such an ADR it would be possible to see how Archivematica began, and show how it has developed. It would serve also as a reference to expose gaps in design surrounding new features, for example, expansion of dashboard capabilities beyond listing AIPs, i.e. when a feature might require a more fundamental redesign of Archivematica's first principles.

**Comment by sevein** [comment]
http://adr.archivematica.org/0010-archivematica-original-design-principles.html
